[workspace]
resolver = "2"
members = ["blocks", "blocks-web"]

[workspace.dependencies]
log = "0.4"
wgpu = { version = "24.0.1", features = ["wgsl"] }
winit = { version = "0.29", features = ["rwh_05"] }

blocks.path = "blocks"
