[package]
name = "blocks"
version = "0.1.0"
edition = "2021"

[dependencies]
pollster = { version = "0.4.0", features = ["macro"] }

wgpu.workspace = true
winit.workspace = true

blocks-renderer.workspace = true
