[package]
name = "blocks-renderer"
version = "0.1.0"
edition = "2021"

[dependencies]
image = { version = "0.25.5", features = ["png"] }

bytemuck.workspace = true
glam.workspace = true
log.workspace = true
wgpu.workspace = true
winit.workspace = true

blocks-game.workspace = true
